export const sharedActionTypes = {
    REINITIALIZE: "REINITIALIZE",
};
export const otherUserProfileModalActionTypes = {
    SET_VISIBILITY: "SET_OTHER_USER_PROFILE_MODAL_VISIBILITY",
    SET_USER_ID: "SET_OTHER_USER_PROFILE_MODAL_USER_ID",
    SET_INFO: "SET_OTHER_USER_PROFILE_MODAL_INFO",
    SET_PHOTOS: "SET_OTHER_USER_PROFILE_MODAL_PHOTOS",
    SET_HOBBIES: "SET_OTHER_USER_PROFILE_MODAL_HOBBIES",
    CLEAN: "CLEAN_OTHER_USER_PROFILE_MODAL",
};

export const userInfoActionTypes = {
    SET_USER_INFO: "SET_USER_INFO",
};
export const hobbiesActionTypes = {
    SET_HOBBIES: "SET_HOBBIES",
};
export const photosActionTypes = {
    SET_PHOTOS: "SET_PHOTOS",
};

export const friendsActionTypes = {
    SET_FRIENDS: "SET_FRIENDS",

    SET_STRANGERS: "SET_STRANGERS",
    TOGGLE_STRANGERS_LOADING: "TOGGLE_STRANGERS_LOADING",

    SET_FRIENDS_FILTER: "SET_FRIENDS_FILTER",
    SET_STRANGERS_FILTER: "SET_STRANGERS_FILTER",

    SET_REQUESTS: "SET_REQUESTS",
    TOGGLE_REQUESTS_VISIBILITY: "TOGGLE_REQUESTS_VISIBILITY",
};

export const chatListActionTypes = {
    SET_CHAT_LIST: "SET_CHAT_LIST",
    TOGGLE_LOADING: "TOGGLE_CHAT_LIST_LOADING",
};

export const chatActionTypes = {
    SET_OTHER_USER_ID: "SET_OTHER_DIALOGUE_MEMBER_ID", //для websocket
    SET_OTHER_USER: "SET_OTHER_DIALOGUE_MEMBER",
    SET_CHAT_ID: "SET_CHAT_ID",
    SET_MESSAGES: "SET_CHAT_MESSAGES",
    SET_IS_SENDING: "SET_IS_SENDING_MESSAGE",
    CLEAR: "CLEAR_CHAT",
};

export const notificationsActionTypes = {
    SET_NOTIFICATIONS: "SET_NOTIFICATIONS",
};
export const onlineDataActionTypes = {
    SET_ONLINE_STATUSES: "SET_ONLINE_DATA_ONLINE_STATUSES",
};

export const dictionariesActionTypes = {
    SET_CITIES: "SET_CITIES_DICTIONARY",
    SET_INTERESTS: "SET_INTERESTS_DICTIONARY",
    SET_FRIENDS_STATUSES: "SET_FRIENDS_STATUSES_DICTIONARY",
};
