export const sharedActionTypes = {
    REINITIALIZE: "REINITIALIZE",
};
export const otherUserProfileModalActionTypes = {
    SET_VISIBILITY: "SET_OTHER_USER_PROFILE_MODAL_VISIBILITY",
    SET_USER_ID: "SET_OTHER_USER_PROFILE_MODAL_USER_ID",
    SET_INFO: "SET_OTHER_USER_PROFILE_MODAL_INFO",
    SET_PHOTOS: "SET_OTHER_USER_PROFILE_MODAL_PHOTOS",
    SET_HOBBIES: "SET_OTHER_USER_PROFILE_MODAL_HOBBIES",
    CLEAN: "CLEAN_OTHER_USER_PROFILE_MODAL",
};

export const userInfoActionTypes = {
    SET_USER_INFO: "SET_USER_INFO",
};
export const hobbiesActionTypes = {
    SET_HOBBIES: "SET_HOBBIES",
};
export const photosActionTypes = {
    SET_PHOTOS: "SET_PHOTOS",
};

export const friendsActionTypes = {
    SET_FRIENDS: "SET_FRIENDS",

    SET_STRANGERS: "SET_STRANGERS",
    TOGGLE_STRANGERS_LOADING: "TOGGLE_STRANGERS_LOADING",

    SET_FRIENDS_FILTER: "SET_FRIENDS_FILTER",
    SET_STRANGERS_FILTER: "SET_STRANGERS_FILTER",

    SET_REQUESTS: "SET_REQUESTS",
    TOGGLE_REQUESTS_VISIBILITY: "TOGGLE_REQUESTS_VISIBILITY",
};

export const chatsActionTypes = {
    SET_CHATS: "SET_CHATS",
    TOGGLE_LOADING: "TOGGLE_CHATS_LOADING",
};

export const chatActionTypes = {
    SET_MEMBERS: "SET_CHAT_MEMBERS",
    SET_CHAT_ID: "SET_CHAT_ID",
    SET_MESSAGES: "SET_CHAT_MESSAGES",
};

export const notificationsActionTypes = {
    SET_NOTIFICATIONS: "SET_NOTIFICATIONS",
};

export const dictionariesActionTypes = {
    SET_CITIES: "SET_CITIES_DICTIONARY",
    SET_INTERESTS: "SET_INTERESTS_DICTIONARY",
    SET_FRIENDS_STATUSES: "SET_FRIENDS_STATUSES_DICTIONARY",
};
