export const userInfoActionTypes = {
    SET_USER_INFO: "SET_USER_INFO",
    CLEAR_USER_INFO: "CLEAR_USER_INFO",
};
export const hobbiesActionTypes = {
    SET_HOBBIES: "SET_HOBBIES",
};
export const photosActionTypes = {
    SET_PHOTOS: "SET_PHOTOS",
};

export const friendsActionTypes = {
    SET_FRIENDS: "SET_FRIENDS",
    
    SET_STRANGERS: "SET_STRANGERS",
    TOGGLE_STRANGERS_LOADING: 'TOGGLE_STRANGERS_LOADING',

    SET_FRIENDS_FILTER: "SET_FRIENDS_FILTER",
    SET_STRANGERS_FILTER: "SET_STRANGERS_FILTER",

    SET_REQUESTS: 'SET_REQUESTS',
    TOGGLE_REQUESTS_VISIBILITY: 'TOGGLE_REQUESTS_VISIBILITY',
    SET_REQUESTS_LOADING: 'SET_REQUESTS_LOADING',
};

export const notificationsActionTypes = {
    SET_NOTIFICATIONS: "SET_NOTIFICATIONS",
};

export const dictionariesActionTypes = {
    SET_CITIES: "SET_CITIES_DICTIONARY",
    SET_INTERESTS: "SET_INTERESTS_DICTIONARY",
    SET_FRIENDS_STATUSES: "SET_FRIENDS_STATUSES_DICTIONARY",
};
